import { db } from "./firebase";
import { doc, getDoc } from "firebase/firestore";

const mapGovernorateToAlbarq = (governorate: string): string => {
  const mapping: { [key: string]: string } = {
    'بغداد': 'BGD',
    'بصر': 'BSR',
    'اربيل': 'ERB',
    'أربيل': 'ERB',
    'ديال': 'DYL',
    'اديال': 'DYL',
    'سليماني': 'SUL',
    'كركوك': 'KIR',
    'نينو': 'NIN',
    'موصل': 'NIN',
    'دهوك': 'DHK',
    'انبار': 'ANB',
    'أنبار': 'ANB',
    'رمادي': 'ANB',
    'بابل': 'BBL',
    'حلة': 'BBL',
    'ذي قار': 'DHQ',
    'ناصرية': 'DHQ',
    'ديواني': 'QAD',
    'قادسي': 'QAD',
    'كربلا': 'KAR',
    'ميسان': 'MYS',
    'عمارة': 'MYS',
    'مثنى': 'MUT',
    'سماوة': 'MUT',
    'نجف': 'NJF',
    'صلاح الدين': 'SAL',
    'تكريت': 'SAL',
    'واسط': 'WAS',
    'كوت': 'WAS',
  };
  
  const normalized = (governorate || '').trim().replace(/محافظة|محافضة/g, '').trim().replace(/^(ال|أل|إل)/, '').trim();
  
  for (const key in mapping) {
    if (normalized.includes(key)) {
      return mapping[key];
    }
  }
  
  return 'BGD'; // Default to Baghdad if not found
};

export const createAlbarqShipment = async (userId: string, orderData: any) => {
  try {
    // 1. Read API Key and Store ID from Firestore
    let integrationRef = doc(db, 'users', userId, 'integrations', 'albarq');
    let docSnap = await getDoc(integrationRef);
    
    // Fallback to default_tenant since the settings page currently saves there
    if (!docSnap.exists()) {
      integrationRef = doc(db, 'users', 'default_tenant', 'integrations', 'albarq');
      docSnap = await getDoc(integrationRef);
    }

    if (!docSnap.exists()) {
      throw new Error('MISSING_CREDENTIALS');
    }
    
    const { apiKey, storeId } = docSnap.data();
    
    if (!apiKey || !storeId) {
      throw new Error('MISSING_CREDENTIALS');
    }
    
    // 2. Map Governorate
    const governorateName = orderData.customerCity || orderData.governorate || '';
    const governorateCode = mapGovernorateToAlbarq(governorateName);
    
    const itemsText = orderData.items && orderData.items.length > 0
      ? orderData.items.map((it: any) => `${it.productName || it.name} (${it.quantity})`).join(' - ')
      : 'طلب من المتجر';

    const areaName = orderData.customerArea || orderData.area || orderData.region || '';
    const baseAddress = orderData.customerAddress || orderData.address || governorateName || 'العنوان غير محدد';
    const finalAddress = areaName ? `${areaName} - ${baseAddress}` : baseAddress;

    // 3. Prepare payload based on the provided JSON structure
    const payload = [
      {
        recipientPhone: orderData.customerPhone || orderData.phone1 || orderData.phone || '',
        receiptNumber: orderData.orderNumber || orderData.id,
        recipientName: orderData.customerName || 'عميل',
        governorate: governorateCode,
        storeID: Number(storeId),
        recipientAddress: finalAddress,
        details: itemsText,
        totalCost: Number(orderData.totalAmount || 0) + Number(orderData.deliveryCost || 0),
        deliveryType: "NORMAL",
        notes: orderData.notes || '',
        quantity: 1
      }
    ];

    // 4. Make API Request
    const endpoint = 'https://api.albarqiq.net/api/v1/orders/create'; 
    
    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey
      },
      body: JSON.stringify(payload)
    });
    
    const textData = await response.text();
    let responseData;
    try {
      responseData = JSON.parse(textData);
    } catch (e) {
      if (!response.ok) {
        throw new Error(`API Error: ${response.status} - ${textData.substring(0, 100)}`);
      }
      throw new Error('رد غير متوقع من الخادم.');
    }

    if (!response.ok) {
      throw new Error(responseData.message || responseData.error || 'فشل إرسال الطلب لشركة البرق');
    }
    
    if (responseData.status === 'error' || responseData.success === false) {
       throw new Error(responseData.message || 'تم الرفض من قبل نظام البرق');
    }

    // Try to extract the real receipt number generated by Al-Barq
    const albarqGeneratedId = 
      responseData.receiptNumber || 
      responseData.orderId || 
      responseData.id || 
      (responseData.data && (responseData.data.receiptNumber || responseData.data.orderId || responseData.data.id)) || 
      (Array.isArray(responseData.data) && responseData.data[0] && (responseData.data[0].receiptNumber || responseData.data[0].orderId || responseData.data[0].id));

    return {
      success: true,
      receiptNumber: albarqGeneratedId || orderData.orderNumber || orderData.id,
      data: responseData
    };

  } catch (error: any) {
    if (error.message === 'MISSING_CREDENTIALS') {
      throw new Error('يرجى إدخال بيانات الربط (مفتاح API ومعرف المتجر) الخاصة بشركة البرق من الإعدادات.');
    }
    console.error('Albarq API Error:', error);
    throw new Error(error.message || 'فشل الاتصال بشركة البرق.');
  }
};
